# Site settings
title: TTPCG
#email: your-email@domain.com
description: Website dedicated to the Penetecostal Church of God Trinidad and Tobago- Youths
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://youth.ttpcg.org" # the base hostname & protocol for your site
permalink: /blog/:year/:month/:day/:title/
# Build settings
markdown: kramdown

pages_list:      
  home: '/' 
  leaders: '/leaders/'
  events: '/events/'
  photos: '/photos/'
  videos: '/videos/'
  blog: '/blog/'
  live: '/live/'
